### PR TITLE
Fix build with exiv 0.28

### PR DESCRIPTION
**Pull request by listout**
With exiv 0.28 we're getting error such as:

> ImageLounge/src/DkCore/DkMetaData.h:151:23: error: ‘AutoPtr’ in ‘class Exiv2::Image’ does not name a type
>   151 |         Exiv2::Image::AutoPtr loadSidecar(const QString& filePath) const;
>       |                       ^~~~~~~
> ImageLounge/src/DkCore/DkMetaData.h:160:23: error: ‘AutoPtr’ in ‘class Exiv2::Image’ does not name a type
>   160 |         Exiv2::Image::AutoPtr mExifImg;
>       |                       ^~~~~~~

...and so on.

First discovered in Gentoo Linux.

Bug: https://bugs.gentoo.org/906488

### CODE REVIEW

**Comment by listout** [comment]
Also can someone make a 3.17 tag for nomacs/nomacs-plugins. Helps in maintaining the package for us.

**Comment by novomesk** [comment]
Thank you for this patch, it is a valuable feedback.

However, it won't be accepted in this form because the appveyor build failed (it uses old version of exiv2 and MSVC on Windows).

Meanwhile, I am preparing alternative fix in https://github.com/nomacs/nomacs/pull/983

I don't have rights for https://github.com/nomacs/nomacs-plugins , most probably there won't be updates there. Only if we create some fork.
