### ISSUE TITLE
nomacs FTBFS in src/DkCore/DkUtils.cpp

### ISSUE THREAD

**Issue by agaida** [nomacs/nomacs#59]
`nomacs/snapshot/src/DkCore/DkUtils.cpp:67:9: error: expected primary-expression before ‘while’
`

**Comment by diemmarkus** [comment]
hi,
I was working on Qt 5.2.1 compatibility (for Ubuntu 14.04) - and left it over night. It is be fixed by now.
thank you

**Comment by diemmarkus** [comment]
btw is there an official debian package planned? (I'd love to see that : )

**Comment by agaida** [comment]
no - not planned, we already have it :)
https://tracker.debian.org/pkg/nomacs

**Comment by sfiel** [comment]
oh, we didn't noticed that, great news ... thanks for packaging!
